### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by 1021331023** [SAGNIKMJR/few-shot-rir#1]
Hello!

I am trying to train the model in 8 NVIDIA GeForce RTX 3090 and it costs 16 min per epoch.
As the default config, it should train it 60000 epochs, it takes too much time.

I was wondering how long the result of Table 1 on the paper costs.

Thanks!

**Comment by SAGNIKMJR** [comment]
I actually stopped training, which it converged around 120-140 epochs. I will clarify this in the next arxiv version.

**Comment by 1021331023** [comment]
Thanks a lot for the answer!
